/* Lightweight OOXML import/export. Export templates are authored with openpyxl.
 * ZIP reading uses native DecompressionStream; no network or third-party runtime. */
(() => {
'use strict';
const enc=new TextEncoder(),dec=new TextDecoder('utf-8');
const DAY=86400000;
const names=['Pazartesi','Sal\u0131','\u00c7ar\u015famba','Per\u015fembe','Cuma','Cumartesi'];
const xesc=v=>String(v??'').replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const col=n=>{let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;};
const add=(s,n)=>new Date(new Date(s+'T12:00:00Z').getTime()+n*DAY).toISOString().slice(0,10);
const serial=s=>Math.round((Date.parse(s+'T00:00:00Z')-Date.UTC(1899,11,30))/DAY);
const fmt=s=>s.split('-').reverse().join('.');
const stat=a=>({total:a.length,onsite:a.filter(x=>x.onsite).length,t1:a.filter(x=>x.t1).length,done:a.filter(x=>x.done).length,pending:a.filter(x=>!x.done).length});
const crcTable=Uint32Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
function crc32(b){let c=0xffffffff;for(const v of b)c=crcTable[(c^v)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
function zipStore(files){const parts=[],central=[];let offset=0,centralSize=0;const now=new Date();const date=((Math.max(1980,now.getFullYear())-1980)<<9)|((now.getMonth()+1)<<5)|now.getDate();const time=(now.getHours()<<11)|(now.getMinutes()<<5)|(now.getSeconds()>>1);
 for(const [name,text] of Object.entries(files)){const n=enc.encode(name),data=enc.encode(text),crc=crc32(data);const h=new Uint8Array(30+n.length),d=new DataView(h.buffer);d.setUint32(0,0x04034b50,true);d.setUint16(4,20,true);d.setUint16(6,0x800,true);d.setUint16(10,time,true);d.setUint16(12,date,true);d.setUint32(14,crc,true);d.setUint32(18,data.length,true);d.setUint32(22,data.length,true);d.setUint16(26,n.length,true);h.set(n,30);parts.push(h,data);const c=new Uint8Array(46+n.length),v=new DataView(c.buffer);v.setUint32(0,0x02014b50,true);v.setUint16(4,20,true);v.setUint16(6,20,true);v.setUint16(8,0x800,true);v.setUint16(12,time,true);v.setUint16(14,date,true);v.setUint32(16,crc,true);v.setUint32(20,data.length,true);v.setUint32(24,data.length,true);v.setUint16(28,n.length,true);v.setUint32(42,offset,true);c.set(n,46);central.push(c);offset+=h.length+data.length;centralSize+=c.length;}
 const end=new Uint8Array(22),e=new DataView(end.buffer);e.setUint32(0,0x06054b50,true);e.setUint16(8,central.length,true);e.setUint16(10,central.length,true);e.setUint32(12,centralSize,true);e.setUint32(16,offset,true);return new Blob([...parts,...central,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
}
function cell(ref,value,style,formula=null){if(formula!=null)return `<c r="${ref}" s="${style}"><f>${xesc(formula)}</f><v>${Number(value)||0}</v></c>`;if(typeof value==='number')return `<c r="${ref}" s="${style}"><v>${Number.isFinite(value)?value:0}</v></c>`;return `<c r="${ref}" s="${style}" t="inlineStr"><is><t xml:space="preserve">${xesc(value)}</t></is></c>`;}
function row(r,vals,styles,height=23){return `<row r="${r}" ht="${height}" customHeight="1">${vals.map((v,i)=>cell(col(i)+r,v,Array.isArray(styles)?styles[i]??styles[0]:styles)).join('')}</row>`;}
function replaceSheet(xml,rows,lastCol,lastRow){return xml.replace(/<sheetData>[\s\S]*?<\/sheetData>/,`<sheetData>${rows}</sheetData>`).replace(/<dimension ref="[^"]*"\s*\/>/,`<dimension ref="A1:${lastCol}${lastRow}"/>`);}
function registrySheet(base,s,data,template,demo){const headers=['PLAKA','M\u00dc\u015eTER\u0130','BEYANNAME','NAKL\u0130YEC\u0130','RUHSAT'];const title=template?'PCS TRANS\u0130T YYS | PLAKA KAYIT \u015eABLONU':'PCS TRANS\u0130T YYS | PLAKA KAYITLARI';let rows=row(1,[`${demo?'\u00d6RNEK VER\u0130 | ':''}${title}`],s.title,35)+row(2,[template?'Plaka ve m\u00fc\u015fteri zorunludur. Ba\u015fl\u0131klar\u0131 de\u011fi\u015ftirmeden 5. sat\u0131rdan itibaren doldurun.':'Veri kayna\u011f\u0131: Uygulamadaki manuel veya Excel\u2019den al\u0131nm\u0131\u015f ana plaka kay\u0131tlar\u0131.'],s.subtitle,27)+row(4,headers,s.header,28);const records=template?Array.from({length:25},()=>({})):data;for(let i=0;i<records.length;i++){const r=records[i];rows+=row(i+5,[r.plate||'',r.customer||'',r.declaration||'',r.carrier||'',r.registration||''],template?s.input:s.linked);}return replaceSheet(base,rows,'E',Math.max(5,records.length+4));}
function opSheet(base,s,rowsData,title,note){let rows=row(1,[title],s.title,35)+row(2,[note],s.subtitle,27)+row(4,['#','TES\u0130STE','T1 YAZILDI','\u0130\u015eLEMLER B\u0130TT\u0130','M\u00dc\u015eTER\u0130','BEYANNAME','PLAKA','NAKL\u0130YEC\u0130','RUHSAT','GEL\u0130\u015e TAR\u0130H\u0130','SAAT','NOT'],s.header,32);const a=rowsData.slice().sort((x,y)=>x.date.localeCompare(y.date)||(x.time||'99:99').localeCompare(y.time||'99:99'));for(let i=0;i<a.length;i++){const r=a[i];rows+=row(i+5,[i+1,r.onsite?'EVET':'HAYIR',r.t1?'EVET':'HAYIR',r.done?'EVET':'HAYIR',r.customer,r.declaration,r.plate,r.carrier,r.registration,serial(r.date),r.time,r.note],[s.muted,s.status,s.status,s.status,s.text,s.text,s.input,s.text,s.text,s.date,s.muted,s.muted],26);}return replaceSheet(base,rows,'L',Math.max(5,a.length+4));}
function summarySheet(base,s,data,rowsData){const ds=Array.from({length:6},(_,i)=>add(data.monday,i)),last=Math.max(5,rowsData.length+4),pano="'PANO'",range=k=>`${pano}!$${k}$5:$${k}$${last}`;const st=stat(rowsData);let rows=row(1,[`${data.demo?'\u00d6RNEK VER\u0130 | ':''}PCS TRANS\u0130T YYS | ${data.selectedDate?'G\u00dcNL\u00dcK':'HAFTALIK'} \u00d6ZET`],s.title,35)+row(2,[data.selectedDate?`${fmt(data.selectedDate)} | Yaln\u0131zca bu g\u00fcn\u00fcn geli\u015fleri aktar\u0131ld\u0131.`:`${data.year} | ${data.week}. Hafta | ${fmt(ds[0])} - ${fmt(ds[5])}`],s.subtitle,27)+row(5,['G\u00dcN','TAR\u0130H','ARA\u00c7','TES\u0130STE \u0130\u015eARETL\u0130','T1 YAZILDI','TAMAMLANAN','BEKLEYEN'],s.header,30);
 for(let i=0;i<6;i++){const r=i+6,counts=stat(rowsData.filter(x=>x.date===ds[i]));rows+=`<row r="${r}" ht="26" customHeight="1">`+cell('A'+r,names[i],s.text)+cell('B'+r,serial(ds[i]),s.date)+cell('C'+r,counts.total,s.integer,`COUNTIF(${range('J')},B${r})`)+cell('D'+r,counts.onsite,s.integer,`COUNTIFS(${range('J')},B${r},${range('B')},"EVET")`)+cell('E'+r,counts.t1,s.integer,`COUNTIFS(${range('J')},B${r},${range('C')},"EVET")`)+cell('F'+r,counts.done,s.integer,`COUNTIFS(${range('J')},B${r},${range('D')},"EVET")`)+cell('G'+r,counts.pending,s.integer,`C${r}-F${r}`)+'</row>';}
 rows+='<row r="13" ht="29" customHeight="1">'+cell('A13','TOPLAM',s.total)+cell('B13','',s.total)+['C','D','E','F','G'].map((c,i)=>cell(c+'13',[st.total,st.onsite,st.t1,st.done,st.pending][i],s.total,`SUM(${c}6:${c}11)`)).join('')+'</row>';
 rows+='<row r="15" ht="27" customHeight="1">'+cell('A15','TAMAMLANMA ORANI',s.subtitle)+cell('D15',st.total?st.done/st.total:0,s.percent,'IFERROR(F13/C13,0)')+'</row>';
 rows+=row(17,['Veri kayna\u011f\u0131: Uygulamadaki yerel geli\u015f kay\u0131tlar\u0131. Her geli\u015f ayr\u0131 say\u0131l\u0131r.'],s.subtitle,25)+row(18,['TES\u0130STE say\u0131s\u0131 i\u015faretli kutular\u0131n toplam\u0131d\u0131r; fiziksel \u00e7\u0131k\u0131\u015f takibi de\u011fildir.'],s.subtitle,25)+row(19,['Bu dosya rapor kopyas\u0131d\u0131r. Uygulamaya tam geri y\u00fckleme i\u00e7in JSON yede\u011fini kullan\u0131n.'],s.subtitle,25);
 return replaceSheet(base,rows,'G',19);
}
function panoWorkbook(data){
 const ds=Array.from({length:6},(_,i)=>add(data.monday,i));
 const all=data.state.visits.filter(x=>ds.includes(x.date)&&(!data.selectedDate||x.date===data.selectedDate));
 const so=v=>v.sort_order==null?Infinity:v.sort_order;
 const tier=v=>v.done?0:(v.onsite&&v.t1)?1:(v.onsite||v.t1)?2:3;
 const custPrio=Array.isArray(data.customerPriority)?data.customerPriority:[];
 const prio=name=>{const c=String(name||'').toLocaleUpperCase('tr-TR');const i=custPrio.findIndex(e=>e.match&&c.includes(String(e.match).toLocaleUpperCase('tr-TR')));return i<0?Infinity:i;};
 const block={};for(const v of all){const k=v.customer||'',c=String(v.createdAt||'');if(!(k in block)||c<block[k])block[k]=c;}
 const auto=(a,b)=>{const ka=a.customer||'',kb=b.customer||'',ba=block[ka]||'',bb=block[kb]||'',pa=prio(ka),pb=prio(kb);
  return (!a.customer)-(!b.customer)||(pa-pb)||(ba<bb?-1:ba>bb?1:0)||(ka!==kb?ka.localeCompare(kb,'tr'):0)||tier(a)-tier(b)||(a.time||'99:99').localeCompare(b.time||'99:99')||String(a.createdAt||'').localeCompare(String(b.createdAt||''));};
 const rows=all.slice().sort((a,b)=>a.date.localeCompare(b.date)||(so(a)===so(b)?auto(a,b):so(a)-so(b)));
 const first=8,last=Math.max(first,first+rows.length-1),CK='\u2611',UN='\u2610',LAST='P';
 const R={},H={};const put=(r,c,v,s,f)=>{(R[r]=R[r]||[]).push([c,cell(col(c)+r,v,s,f)]);};
 for(let c=0;c<=15;c++)put(1,c,c?'':'PCS TRANS\u0130T  /  ARA\u00c7 TAKP PANOSU'.replace('TAKP','TAK\u0130P'),1);H[1]=32;
 const wk=data.selectedDate?`${fmt(data.selectedDate)}  \u00b7  G\u00dcNL\u00dcK`:`${data.week}. HAFTA  \u00b7  ${fmt(ds[0])} \u2013 ${fmt(ds[5])}`;
 put(2,0,wk,2);for(let c=1;c<=4;c++)put(2,c,'',2);put(2,5,`${CK} i\u015faretli, ${UN} bo\u015f. Her geli\u015f ayr\u0131 sat\u0131r olarak say\u0131l\u0131r.`,23);H[2]=26;
 const st=stat(rows),rng=k=>`${k}${first}:${k}${last}`;
 const kp=[['TOPLAM ARA\u00c7',st.total,`COUNTA(${rng('D')})`],['TES\u0130STE',st.onsite,`COUNTIF(${rng('H')},"${CK}")`],['T1 YAZILDI',st.t1,`COUNTIF(${rng('I')},"${CK}")`],['TAMAMLANDI',st.done,`COUNTIF(${rng('J')},"${CK}")`]];
 const sub=data.selectedDate?'g\u00fcn toplam\u0131':`${data.week}. hafta toplam\u0131`;
 kp.forEach(([l,v,f],i)=>{put(3,2+i,l,3+i);put(4,2+i,v,7+i,f);put(5,2+i,sub,11);});H[3]=22;H[4]=40;H[5]=18;H[6]=8;
 ['HAFTA','G\u00dcN','M\u00dc\u015eTER\u0130','PLAKA','BEYANNAME','NAKL\u0130YEC\u0130','RUHSAT','TES\u0130STE','T1 YAZILDI','\u0130\u015eLEMLER B\u0130TT\u0130'].forEach((h,i)=>put(7,i,h,12));H[7]=30;
 rows.forEach((v,i)=>{const r=first+i,di=ds.indexOf(v.date);H[r]=24;
  put(r,0,`${data.week}. HAFTA`,15);put(r,1,`${di+1} ${names[di]}`,15);put(r,2,v.customer||'',14);put(r,3,v.plate||'',16);put(r,4,v.declaration||'',13);put(r,5,v.carrier||'',13);put(r,6,v.registration||'',15);
  put(r,7,v.onsite?CK:UN,17);put(r,8,v.t1?CK:UN,17);put(r,9,v.done?CK:UN,17);});
 const groups=new Map();for(const v of rows){const k=v.customer||'(M\u00dc\u015eTER\u0130 YOK)';const g=groups.get(k)||{n:0,o:0,t:0,d:0};g.n++;g.o+=v.onsite?1:0;g.t+=v.t1?1:0;g.d+=v.done?1:0;groups.set(k,g);}
 const list=[...groups].sort((a,b)=>b[1].n-a[1].n||(a[0][0]==='(')-(b[0][0]==='(')||a[0].localeCompare(b[0],'tr'));
 put(8,11,'M\u00dc\u015eTER\u0130 BAZINDA ARA\u00c7',18);for(let c=12;c<=15;c++)put(8,c,'',18);
 ['M\u00dc\u015eTER\u0130','ARA\u00c7','TES\u0130STE','T1 YAZILDI','B\u0130TT\u0130'].forEach((h,i)=>put(9,11+i,h,12));H[9]=H[9]||26;
 const safe=k=>!/[*?~]/.test(k)&&!k.startsWith('(');const cr=`$C$${first}:$C$${last}`;
 list.forEach(([k,g],i)=>{const r=10+i;H[r]=H[r]||24;put(r,11,k,19);
  put(r,12,g.n,20,safe(k)?`COUNTIF(${cr},L${r})`:null);
  put(r,13,g.o,20,safe(k)?`COUNTIFS(${cr},L${r},$H$${first}:$H$${last},"${CK}")`:null);
  put(r,14,g.t,20,safe(k)?`COUNTIFS(${cr},L${r},$I$${first}:$I$${last},"${CK}")`:null);
  put(r,15,g.d,20,safe(k)?`COUNTIFS(${cr},L${r},$J$${first}:$J$${last},"${CK}")`:null);});
 const tr=10+list.length,s0=10,s1=tr-1;H[tr]=H[tr]||26;put(tr,11,'TOPLAM',21);
 [['M',st.total],['N',st.onsite],['O',st.t1],['P',st.done]].forEach(([c,v],i)=>put(tr,12+i,v,22,list.length?`SUM(${c}${s0}:${c}${s1})`:null));
 const maxRow=Math.max(last,tr);let sd='';
 for(let r=1;r<=maxRow;r++){const cells=(R[r]||[]).sort((a,b)=>a[0]-b[0]).map(x=>x[1]).join('');sd+=`<row r="${r}"${H[r]?` ht="${H[r]}" customHeight="1"`:''}>${cells}</row>`;}
 const widths=[11,14,36,30,30,36,13,12,14,16,3,32,10,11,13,10];
 const cols=widths.map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join('');
 const sheet=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetPr><pageSetUpPr fitToPage="1"/></sheetPr><dimension ref="A1:${LAST}${maxRow}"/><sheetViews><sheetView showGridLines="0" tabSelected="1" workbookViewId="0"><pane ySplit="7" topLeftCell="A8" activePane="bottomLeft" state="frozen"/><selection pane="bottomLeft" activeCell="A8" sqref="A8"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="20"/><cols>${cols}</cols><sheetData>${sd}</sheetData><autoFilter ref="A7:J${last}"/><mergeCells count="3"><mergeCell ref="A1:${LAST}1"/><mergeCell ref="A2:E2"/><mergeCell ref="L8:P8"/></mergeCells><pageMargins left="0.4" right="0.4" top="0.5" bottom="0.5" header="0.3" footer="0.3"/><pageSetup paperSize="9" orientation="landscape" fitToWidth="1" fitToHeight="0"/></worksheet>`;
 const fnt=(x,c,sz,n='Calibri')=>`<font>${x}<sz val="${sz}"/><color rgb="FF${c}"/><name val="${n}"/><family val="2"/></font>`;
 const top=c=>`<border><left/><right/><top style="medium"><color rgb="FF${c}"/></top><bottom/><diagonal/></border>`;
 const thin=`<border><left style="thin"><color rgb="FFBFBFBF"/></left><right style="thin"><color rgb="FFBFBFBF"/></right><top style="thin"><color rgb="FFBFBFBF"/></top><bottom style="thin"><color rgb="FFBFBFBF"/></bottom><diagonal/></border>`;
 const xf=(fo,fi,bo,h,extra='')=>`<xf numFmtId="0" fontId="${fo}" fillId="${fi}" borderId="${bo}" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="${h}" vertical="center"${extra}/></xf>`;
 const styles=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="13">${fnt('','000000',11)}${fnt('<b/>','FFFFFF',16)}${fnt('<b/>','1F3864',12)}${fnt('<b/>','595959',10)}${fnt('<b/>','1F6FD0',24)}${fnt('<b/>','2E9E44',24)}${fnt('<b/>','D69E00',24)}${fnt('<b/>','8E24AA',24)}${fnt('<i/>','8C8C8C',9)}${fnt('<b/>','1A1A1A',11)}${fnt('<b/>','C00000',11)}${fnt('','1A1A1A',13,'Segoe UI Symbol')}${fnt('<i/>','7F7F7F',9)}</fonts><fills count="5"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF1F3864"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFFD700"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFFF2CC"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="6"><border><left/><right/><top/><bottom/><diagonal/></border>${thin}${top('1F6FD0')}${top('2E9E44')}${top('D69E00')}${top('8E24AA')}</borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="24"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>${xf(1,2,0,'left',' indent="1"')}${xf(2,0,0,'left',' indent="1"')}${xf(3,0,2,'center')}${xf(3,0,3,'center')}${xf(3,0,4,'center')}${xf(3,0,5,'center')}${xf(4,0,0,'center')}${xf(5,0,0,'center')}${xf(6,0,0,'center')}${xf(7,0,0,'center')}${xf(8,0,0,'center')}${xf(9,3,1,'center',' wrapText="1"')}${xf(0,0,1,'left',' indent="1"')}${xf(10,0,1,'left',' indent="1"')}${xf(0,0,1,'center')}${xf(9,0,1,'center')}${xf(11,0,1,'center')}${xf(9,3,1,'center')}${xf(9,0,1,'left',' indent="1"')}${xf(0,0,1,'center')}${xf(9,4,1,'left',' indent="1"')}${xf(9,4,1,'center')}${xf(12,0,0,'left',' indent="1"')}</cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;
 const files={
  '[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>',
  '_rels/.rels':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
  'xl/workbook.xml':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><bookViews><workbookView/></bookViews><sheets><sheet name="PANO" sheetId="1" r:id="rId1"/></sheets><definedNames><definedName name="_xlnm._FilterDatabase" localSheetId="0" hidden="1">PANO!$A$7:$J$${last}</definedName></definedNames></workbook>`,
  'xl/_rels/workbook.xml.rels':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
  'xl/styles.xml':styles,'xl/worksheets/sheet1.xml':sheet};
 const name=data.selectedDate?`PCS_${data.selectedDate}_GUN.xlsx`:`PCS_${data.year}_${String(data.week).padStart(2,'0')}_HAFTA.xlsx`;
 return {blob:zipStore(files),name};
}function makeWorkbook(data,mode){if(mode!=='registry'&&mode!=='template')return panoWorkbook(data);const regOnly=mode==='registry'||mode==='template',base=regOnly?PCS_TEMPLATES.registry:PCS_TEMPLATES.operations,files={...base.files},s=base.styles;const prefix=data.demo&&mode!=='template'?'ORNEK_':'';let name;
 if(regOnly){files['xl/worksheets/sheet1.xml']=registrySheet(files['xl/worksheets/sheet1.xml'],s,data.state.registry,mode==='template',data.demo&&mode!=='template');name=mode==='template'?'PCS_PLAKA_KAYIT_SABLONU.xlsx':prefix+'PCS_PLAKA_KAYITLARI.xlsx';}
 else{const ds=Array.from({length:6},(_,i)=>add(data.monday,i));const all=data.state.visits.filter(x=>ds.includes(x.date)&&(!data.selectedDate||x.date===data.selectedDate));const range=`${data.year} | ${data.week}. Hafta | ${fmt(ds[0])} - ${fmt(ds[5])}`;const note=(data.selectedDate?`${fmt(data.selectedDate)} | G\u00fcnl\u00fck rapor. `:range+' | ')+'Durumlar EVET/HAYIR olarak aktar\u0131l\u0131r. Plaka tek alan: G s\u00fctunu.';
 files['xl/worksheets/sheet1.xml']=summarySheet(files['xl/worksheets/sheet1.xml'],s,data,all);
 files['xl/worksheets/sheet2.xml']=opSheet(files['xl/worksheets/sheet2.xml'],s,all,`${data.demo?'\u00d6RNEK VER\u0130 | ':''}PCS TRANS\u0130T YYS | PANO`,note);
 for(let i=0;i<6;i++){const path=`xl/worksheets/sheet${i+3}.xml`;files[path]=opSheet(files[path],s,all.filter(v=>v.date===ds[i]),`${data.demo?'\u00d6RNEK VER\u0130 | ':''}${names[i].toLocaleUpperCase('tr-TR')} | ${fmt(ds[i])}`,range+' | G\u00fcn\u00fcn ara\u00e7 geli\u015fleri');}
 files['xl/worksheets/sheet9.xml']=registrySheet(files['xl/worksheets/sheet9.xml'],s,data.state.registry,false,data.demo);name=prefix+(data.selectedDate?`PCS_${data.selectedDate}_GUN.xlsx`:`PCS_${data.year}_${String(data.week).padStart(2,'0')}_HAFTA.xlsx`);
 }
 return {blob:zipStore(files),name};
}
function parseXML(s){const d=new DOMParser().parseFromString(s,'application/xml');if(d.getElementsByTagName('parsererror').length)throw new Error('Excel XML i\u00e7eri\u011fi ge\u00e7erli de\u011fil.');return d;}
const tags=(d,n)=>Array.from(d.getElementsByTagNameNS('*',n));
function resolvePath(base,target){const out=[];for(const part of (target.startsWith('/')?target:base+'/'+target).split('/')){if(!part||part==='.')continue;if(part==='..')out.pop();else out.push(part);}return out.join('/');}
async function unzipReader(file){if(file.size>10*1024*1024)throw new Error('Excel dosyas\u0131 10 MB\u2019tan k\u00fc\u00e7\u00fck olmal\u0131.');const buf=await file.arrayBuffer(),view=new DataView(buf);if(buf.byteLength<22)throw new Error('Ge\u00e7erli bir .xlsx dosyas\u0131 se\u00e7in.');let end=-1;for(let p=buf.byteLength-22;p>=Math.max(0,buf.byteLength-65557);p--)if(view.getUint32(p,true)===0x06054b50){end=p;break;}if(end<0)throw new Error('Dosya bir .xlsx paketi de\u011fil. Eski .xls dosyas\u0131n\u0131 .xlsx olarak kaydedin.');const count=view.getUint16(end+10,true);let p=view.getUint32(end+16,true);if(count>300)throw new Error('Excel dosyas\u0131nda \u00e7ok fazla bile\u015fen var. Yaln\u0131zca plaka sayfas\u0131n\u0131 yeni bir dosyaya kaydedin.');const entries=new Map();let total=0;
 for(let i=0;i<count;i++){if(p+46>buf.byteLength||view.getUint32(p,true)!==0x02014b50)throw new Error('Excel paketi hasarl\u0131.');const flags=view.getUint16(p+8,true),method=view.getUint16(p+10,true),crc=view.getUint32(p+16,true),size=view.getUint32(p+20,true),usize=view.getUint32(p+24,true),nl=view.getUint16(p+28,true),el=view.getUint16(p+30,true),cl=view.getUint16(p+32,true),offset=view.getUint32(p+42,true);if(flags&1)throw new Error('\u015eifreli Excel dosyas\u0131 desteklenmiyor.');if(p+46+nl+el+cl>buf.byteLength)throw new Error('Paket kayd\u0131 eksik.');const name=dec.decode(new Uint8Array(buf,p+46,nl));total+=usize;if(total>32*1024*1024||usize>20*1024*1024)throw new Error('A\u00e7\u0131lm\u0131\u015f Excel i\u00e7eri\u011fi boyut s\u0131n\u0131r\u0131n\u0131 a\u015f\u0131yor.');entries.set(name,{method,size,usize,offset,crc});p+=46+nl+el+cl;}
 return {has:name=>entries.has(name),async text(name){const z=entries.get(name);if(!z)throw new Error('Excel bile\u015feni bulunamad\u0131: '+name);if(z.offset+30>buf.byteLength||view.getUint32(z.offset,true)!==0x04034b50)throw new Error('Excel bile\u015feni hasarl\u0131.');const start=z.offset+30+view.getUint16(z.offset+26,true)+view.getUint16(z.offset+28,true);if(start+z.size>buf.byteLength)throw new Error('Excel verisi eksik.');const compressed=new Uint8Array(buf,start,z.size);let data;
 if(z.method===0)data=compressed;else if(z.method===8){let stream;try{stream=new Blob([compressed]).stream().pipeThrough(new DecompressionStream('deflate-raw'));}catch(e){throw new Error('Bu taray\u0131c\u0131 .xlsx i\u00e7e aktarmay\u0131 desteklemiyor. G\u00fcncel Chrome/Edge veya CSV dosyas\u0131 kullan\u0131n.');}const reader=stream.getReader(),chunks=[];let size=0;for(;;){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>20*1024*1024){await reader.cancel();throw new Error('Excel bile\u015feni \u00e7ok b\u00fcy\u00fck.');}chunks.push(value);}data=new Uint8Array(size);let at=0;for(const c of chunks){data.set(c,at);at+=c.length;}}
 else throw new Error('Excel s\u0131k\u0131\u015ft\u0131rma bi\u00e7imi desteklenmiyor.');if(data.length!==z.usize||crc32(data)!==z.crc)throw new Error('Excel dosyas\u0131n\u0131n b\u00fct\u00fcnl\u00fck kontrol\u00fc ba\u015far\u0131s\u0131z.');return dec.decode(data);}};
}
function headerNorm(s){return String(s||'').toUpperCase().replace(/\u0130/g,'I').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Z0-9]/g,'');}
function convertRows(rows){const aliases={plate:['PLAKA','ARACPLAKASI','CEKICIPLAKASI'],customer:['MUSTERI','MUSTERIADI','MUSTERIBILGISI','FIRMA','UNVAN'],declaration:['BEYANNAME','BEYANNAMENO','BEYANNAMEBILGISI','BEYANNAMEREFERANS'],carrier:['NAKLIYECI','NAKLIYECIFIRMA','NAKLIYECIBILGISI','TASIYICI'],registration:['RUHSAT','RUHSATNO','RUHSATBILGISI']};let start=-1,map={};for(let i=0;i<Math.min(20,rows.length);i++){const normalized=(rows[i]||[]).map(headerNorm),m={};for(const [key,values] of Object.entries(aliases))m[key]=normalized.findIndex(x=>values.includes(x));if(m.plate>=0&&m.customer>=0){start=i;map=m;break;}}if(start<0)throw new Error('\u0130lk 20 sat\u0131rda PLAKA ve M\u00dc\u015eTER\u0130 ba\u015fl\u0131klar\u0131 bulunamad\u0131. Uygulaman\u0131n Excel \u015fablonunu kullan\u0131n.');if(rows.length-start>10001)throw new Error('Tek seferde en fazla 10.000 sat\u0131r al\u0131nabilir.');return rows.slice(start+1).filter(r=>r&&r.some(v=>String(v||'').trim())).map(r=>Object.fromEntries(Object.entries(map).map(([k,index])=>[k,index<0?'':String(r[index]??'')])));}
function parseCSV(text){text=text.replace(/^\uFEFF/,'');const line=text.split(/\r?\n/).find(x=>x.trim())||'';const delimiters=[';',',','\t'];const delimiter=delimiters.sort((a,b)=>line.split(b).length-line.split(a).length)[0];const rows=[];let row=[],field='',quote=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quote){if(ch==='"'&&text[i+1]==='"'){field+='"';i++;}else if(ch==='"')quote=false;else field+=ch;}else if(ch==='"'&&!field)quote=true;else if(ch===delimiter){row.push(field);field='';}else if(ch==='\n'||ch==='\r'){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(field);rows.push(row);row=[];field='';}else field+=ch;}if(quote)throw new Error('CSV dosyas\u0131nda kapanmam\u0131\u015f t\u0131rnak var.');if(field||row.length){row.push(field);rows.push(row);}return rows;}
async function readRegistry(file){if(file.size>10*1024*1024)throw new Error('Dosya en fazla 10 MB olabilir.');if(/\.(csv|tsv)$/i.test(file.name)){const buf=await file.arrayBuffer();let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(buf);}catch(e){text=new TextDecoder('windows-1254').decode(buf);}return convertRows(parseCSV(text));}if(!/\.xlsx$/i.test(file.name))throw new Error('.xlsx, .csv veya .tsv dosyas\u0131 se\u00e7in.');const zip=await unzipReader(file),bookPath='xl/workbook.xml',book=parseXML(await zip.text(bookPath)),rels=parseXML(await zip.text('xl/_rels/workbook.xml.rels'));const sheets=tags(book,'sheet');const sheet=sheets.find(s=>headerNorm(s.getAttribute('name'))==='PLAKAKAYITLARI')||sheets[0];if(!sheet)throw new Error('Excel\u2019de sayfa bulunamad\u0131.');const rid=sheet.getAttribute('r:id')||sheet.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id');const relation=tags(rels,'Relationship').find(r=>r.getAttribute('Id')===rid);if(!relation)throw new Error('Excel sayfa ba\u011flant\u0131s\u0131 bulunamad\u0131.');if(relation.getAttribute('TargetMode')==='External')throw new Error('Harici ba\u011flant\u0131l\u0131 Excel sayfas\u0131 desteklenmiyor.');const path=resolvePath('xl',relation.getAttribute('Target'));let strings=[];const sr=tags(rels,'Relationship').find(r=>r.getAttribute('Type')?.endsWith('/sharedStrings'));if(sr){const sx=parseXML(await zip.text(resolvePath('xl',sr.getAttribute('Target'))));strings=tags(sx,'si').map(si=>tags(si,'t').map(t=>t.textContent).join(''));}
 const doc=parseXML(await zip.text(path)),rows=[];let cells=0;for(const r of tags(doc,'row')){const row=[];const ri=Number(r.getAttribute('r'))-1;if(!Number.isInteger(ri)||ri<0||ri>10020)throw new Error('Sayfa 10.000 sat\u0131r\u0131 a\u015f\u0131yor. Gereksiz bo\u015f sat\u0131rlar\u0131 silin.');for(const c of tags(r,'c')){if(++cells>200000)throw new Error('Excel sayfas\u0131nda \u00e7ok fazla h\u00fccre var.');const letters=(c.getAttribute('r')||'').match(/^[A-Z]+/i)?.[0];if(!letters)continue;let ci=0;for(const ch of letters.toUpperCase())ci=ci*26+ch.charCodeAt(0)-64;ci--;if(ci>100)continue;const type=c.getAttribute('t'),value=tags(c,'v')[0]?.textContent||'';row[ci]=type==='s'?(strings[Number(value)]||''):type==='inlineStr'?tags(c,'t').map(t=>t.textContent).join(''):type==='b'?(value==='1'?'EVET':'HAYIR'):value;}rows[ri]=row;}return convertRows(rows);}
window.PCSXLSX={makeWorkbook,readRegistry};
})();

